### ISSUE TITLE
monitor future package vulnerabilities

### ISSUE THREAD

**Issue by ellieking17** [alphagov/govuk-network-data#39]
For later

We might also want to consider how we monitor for future vulnerabilities, the more packages we have the more checks we need although these can be automated with tools like Snyk:

https://gds-way.cloudapps.digital/standards/tracking-dependencies.html#how-to-manage-third-party-software-dependencies

**Comment by mammykins** [comment]
github seems to be doing this automatically for us, but i can also set up snyk to do this

**Comment by mammykins** [comment]
closing as can't be addressed in the code base
